"use strict";(()=>{var e={};e.id=251,e.ids=[251],e.modules={399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},6005:e=>{e.exports=require("node:crypto")},2847:(e,r,o)=>{o.r(r),o.d(r,{originalPathname:()=>f,patchFetch:()=>h,requestAsyncStorage:()=>m,routeModule:()=>d,serverHooks:()=>v,staticGenerationAsyncStorage:()=>g});var t={};o.r(t),o.d(t,{POST:()=>l});var s=o(9303),n=o(8716),i=o(3131),a=o(7070),p=o(2591);let c=process.env.RESEND_API_KEY,u=c?new p.R(c):null;async function l(e){try{let{name:r,email:o,service:t,preferredDate:s,message:n,conversation:i}=await e.json();if(!r||!o||!t||!s)return a.NextResponse.json({error:"Missing required fields"},{status:400});let p=process.env.EMAIL_TO??process.env.EMAIL_USER??"rjimueltorrecampo@gmail.com";if(!u||!c||!p)return console.error("Resend or email environment variables are not configured"),a.NextResponse.json({error:"Email configuration is missing on the server"},{status:500});let l=[`Name: ${r}`,`Email: ${o}`,`Service: ${t}`,`Preferred date/time: ${s}`,"","Message:",n||"-","","Conversation transcript:",i||"-"].join("\n"),d=process.env.RESEND_FROM??"onboarding@resend.dev",{error:m}=await u.emails.send({from:d,to:p,subject:`New service booking from ${r}`,text:l,html:`<p>New booking request from <strong>${r}</strong>.</p>
<p><strong>Email:</strong> ${o}</p>
<p><strong>Service:</strong> ${t}</p>
<p><strong>Preferred date/time:</strong> ${s}</p>
<p><strong>Message:</strong><br/>${n||"-"}</p>
<hr />
<p><strong>Conversation transcript:</strong></p>
<pre style="white-space:pre-wrap;font-family:system-ui, -apple-system, sans-serif;">${i||"-"}</pre>`});if(m){let e=m.message?.includes("fetch")||m.message?.includes("could not be resolved")||"application_error"===m.name;return console.error("Resend error in /api/book-service:",m),e&&console.error("Hint: Request never reached Resend. Check: internet, firewall/proxy, DNS, or https://status.resend.com"),a.NextResponse.json({error:e?"Could not reach email service. Check your network or try again later.":"Email provider rejected the request"},{status:502})}let{error:g}=await u.emails.send({from:d,to:o,subject:"Booking request received – Jimuel",text:`Hi ${r},

Thanks for your booking request! Jimuel has received your details and will get back to you soon.

Service: ${t}
Preferred date/time: ${s}

Best,
Portfolio`,html:`<p>Hi ${r},</p><p>Thanks for your booking request! Jimuel has received your details and will get back to you soon.</p><p><strong>Service:</strong> ${t}<br/><strong>Preferred date/time:</strong> ${s}</p><p>Best,<br/>Portfolio</p>`});return g&&console.error("Resend confirmation error (notification still sent):",g),a.NextResponse.json({success:!0})}catch(e){return console.error("Error in /api/book-service:",e),a.NextResponse.json({error:"Failed to send booking email"},{status:500})}}let d=new s.AppRouteRouteModule({definition:{kind:n.x.APP_ROUTE,page:"/api/book-service/route",pathname:"/api/book-service",filename:"route",bundlePath:"app/api/book-service/route"},resolvedPagePath:"C:\\Users\\MIS\\Videos\\My-own-page\\app\\api\\book-service\\route.ts",nextConfigOutput:"",userland:t}),{requestAsyncStorage:m,staticGenerationAsyncStorage:g,serverHooks:v}=d,f="/api/book-service/route";function h(){return(0,i.patchFetch)({serverHooks:v,staticGenerationAsyncStorage:g})}}};var r=require("../../../webpack-runtime.js");r.C(e);var o=e=>r(r.s=e),t=r.X(0,[948,972,591],()=>o(2847));module.exports=t})();